# Generated by Django 4.0.1 on 2022-01-19 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.point')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='It looks, like this quiz does not have a description', max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('url', models.URLField(default='No url provided')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.CharField(default='', max_length=100)),
                ('current_points', models.IntegerField(default=0)),
                ('achievements', models.ManyToManyField(related_name='achievements', through='server.AchievementOfUser', to='server.Achievement')),
                ('participating', models.ManyToManyField(related_name='participating', through='server.QuizOfUser', to='server.Quiz')),
                ('points', models.ManyToManyField(related_name='points', through='server.PointOfUser', to='server.Point')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeOfQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.quiz')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.theme')),
            ],
        ),
        migrations.AddField(
            model_name='quizofuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.ManyToManyField(through='server.ThemeOfQuiz', to='server.Theme'),
        ),
        migrations.AddField(
            model_name='pointofuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AddField(
            model_name='achievementofuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
    ]
