# Generated by Django 4.0.1 on 2022-01-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_quiz_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='theme',
            new_name='themes',
        ),
    ]
